### ISSUE TITLE
install requirements

### ISSUE THREAD

**Issue by cdenneen** [tjdevries/config.nvim#2]
Cloned this to clean Ubuntu vm.
Installed neovim, fzf, ripgrep.
Tried to run neovim and got:

```
Error detected while processing /home/chris1/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/chris1/.config/nvim/init.lua:9: attempt to index field 'uv' (a nil value)
stack traceback:
        /home/chris1/.config/nvim/init.lua:9: in main chunk
Error detected while processing /home/chris1/.config/nvim/plugin/misery.lua:
E5113: Error while calling lua chunk: /home/chris1/.config/nvim/plugin/misery.lua:12: Vim:E484: Can't open file /home/tjdevries/plugins/misery.nvim/plugin/misery.lua
stack traceback:
        [C]: in function 'source'
        /home/chris1/.config/nvim/plugin/misery.lua:12: in main chunk
```

**Comment by autokludge** [comment]
This config references local plugins outside the config folder, I would treat this config as a reference and not a 'distro'.

Reading the friendly message:
`E5113: Error while calling lua chunk: /home/chris1/.config/nvim/plugin/misery.lua:12: Vim:E484: Can't open file /home/tjdevries/plugins/misery.nvim/plugin/misery.lua`

``` 
plugins/misery.lua

--[[
--
-- You can ignore this file, it's just for goofy shenanigans
-- related to misery.nvim, not towards my real config
--
--]]
```
misery.nvim allows twitch.tv viewers to send tj "gifts" using twitch.tv points to make the personal nvim config rewrite more 'exciting' 😈

**Comment by tjdevries** [comment]
This isn't for other people to install :) it's just for a reference so people can see what my config looks like!

**Comment by cdenneen** [comment]
@tjdevries I was trying to follow along with the rewrite videos on YouTube. 

Any plans to have repo dedicated to those rewrites so they are a bit more useable? Maybe a video starting with kickstart.nvim and breaking that into configuration files from one large init.lua? 

Maybe even recommendations to expand onto that base with things like tmux-vim-navigator? fugitive or neogit (probably less context switching than lazyGit but could be there as backup)?
