### ISSUE TITLE
C-L-default

### ISSUE THREAD

**Issue by KiLLeRRaT** [tjdevries/config.nvim#4]
Hi Teej,

I learnt the `<C-L>` off you a long time ago in a video to set `nohls`, but just noticed you now override that with `<C-W>l`.  Do you still use `<C-L>` or are you going to remap it elsewhere?

Cheers!

**Comment by tjdevries** [comment]
I don't use <c-l> for nohls, I usually just set something like hitting enter or esc will turn it off if it's currently enabled

**Comment by tjdevries** [comment]
https://github.com/tjdevries/config.nvim/blob/master/plugin/keymaps.lua#L15-L24

**Comment by KiLLeRRaT** [comment]
Excellent, thank you :) I will grab that idea!
